baseURL = 'https://suikaremilia.github.io/'
copyright = "{year}" # To make 2007 - 2022. Just add before {year} example: 2007 - {year}
languageCode = 'en-us'
theme = 'lowkey'
title = 'Red Panda YOLO'
enableRobotsTXT = true

# List Config
summaryLength= 0
paginate = 5

[markup.highlight]
codeFences = true
guessSyntax = true
hl_Lines = ""
lineNoStart = 1
lineNos = false
lineNumbersInTable = false
noClasses = true
style = "emacs"
tabWidth = 4
