baseURL = "https://suikaremilia.github.io/"
buildFuture = true
defaultContentLanguage = "zh-cn"
languageCode = "zh-cn"
title = "小熊猫快站起来"
theme = "m10c"
paginate = 8

favicon = "/favicon.ico"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 2

[params]
  author = "Suika"
  description = "Long forex, Short the world."
  menu_item_separator = "  ✰  "
  [[params.social]]
    icon = "send"
    name = "telegram"
    url = "https://t.me/Suikachat_bot"
  [[params.social]]
    icon = "mail"
    name = "Mail"
    url = "mailto:suika@kadama.eu.org"
  [[params.social]]
    icon = "rss"
    name = "RSS"
    url = "https://suikaremilia.github.io/index.xml"

  [params.style]
    darkestColor = "#242930"
    darkColor = "#353b43"
    lightColor = "#d6d6d6"
    lightestColor = "#d3d3d3"
    primaryColor = "#57cc8a"

  [params.utteranc]
    enable = true
    repo = "suikaremilia/suikaremilia.github.io"
    issueTerm = "pathname"

[markup.highlight]
codeFences = true
guessSyntax = false
hl_Lines = ""
lineNoStart = 1
lineNos = false
lineNumbersInTable = true
noClasses = true
style = "monokai"
tabWidth = 4

[minify.tdewolff.html]
keepWhitespace = true